# .github/workflows/test.yml
name: Tests

on:
  push:
    #branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    #branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: 'pyproject.toml'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch
        pip install .[test,dev]

    - name: Format with ruff
      run: |
        ruff format .
        ruff check . --fix

    - name: Run isort
      run: |
        isort .

    - name: Commit formatting changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git diff --quiet || (git add . && git commit -m "Auto-format code with ruff and isort" && git push)

    - name: Run tests
      run: |
        pytest --cov=torno

    - name: Type check with mypy
      run: |
        mypy src/torno
